apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: lucee-trigger
spec:
  serviceAccountName: pipeline
  # interceptors:
  #   - ref:
  #       name: "github"
  #     params:
  #       - name: "secretRef"
  #         value:
  #           secretName: github-secret
  #           secretKey: secretToken
  #       - name: "eventTypes"
  #         value: ["push"]
  bindings:
    - ref: lucee-app
  template:
    ref: lucee-app
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
