apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: lucee-trigger
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: lucee-app
  template:
    ref: lucee-app
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
type: Opaque
stringData:
  secretToken: "1234567"
