kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-app
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Values.appNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit
