kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:image-puller:pipeline'
  namespace: {{ .Values.appNamespace }}
subjects:
  - kind: ServiceAccount
    name: lucee-app
    namespace: {{ .Values.pipelineNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: 'system:image-puller'