kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-argocd-application-controller
subjects:
  - kind: ServiceAccount
    name: example-argocd-application-controller
    namespace: {{ .Values.argocd.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example-argocd-application-controller
