apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lucee-app
spec:
  destination:
    name: ''
    namespace: {{ .Values.argocd.tenant.namespace }}
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/app
    valueFiles:
      - values-production.yaml
    repoURL: 'https://github.com/ypenn21/lucee-docker.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
